### PR TITLE
Update to v0.2.0

### PR DESCRIPTION
**Pull request by zwelz3**
Release 0.2.0 (M_e)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by zwelz3** [comment]
@conda-forge-admin, please rerender

**Review by sanbales — CHANGES_REQUESTED** [review]
Would suggest changing the PR title to `Update to v0.2.0` or something like that.

**Comment by zwelz3** [comment]
> Would suggest changing the PR title to `Update to v0.2.0` or something like that.

Good suggestion.

**Review by bollwyvl — APPROVED** [review]

**Comment by zwelz3** [comment]
@bollwyvl It doesn't look like I have write access to merge the PR. Can you add me, or merge for me please?

**Comment by bollwyvl** [comment]
@zwelz3 check your email (including spam folders) within a few minutes after this fires, it will likely send you an invitation.

**Pull request merged**
